//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAURANT_MIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int Billid { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Amount { get; set; }
        public int Status { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    }
}
