//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTAURANT_MIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeBoard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NoticeBoard()
        {
            this.Notices = new HashSet<Notices>();
        }
    
        public int NoticeBoardId { get; set; }
        public string NoticeName { get; set; }
        public string Notice { get; set; }
        public Nullable<System.DateTime> NoticeFrom { get; set; }
        public Nullable<System.DateTime> NoticeTo { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notices> Notices { get; set; }
    }
}
